# Written by CampusIoT Dev Team, 2016-2019

version: "2"

services:

# http://docs.grafana.org/installation/docker/
  grafana:
    image: grafana/grafana
#    build:
#      context: ./docker/grafana
#    image: campusiot/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: MY_WEAK_SECRET_PASSWORD_TO_CHANGE
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,mtanda-heatmap-epoch-panel,briangann-gauge-panel,jdbranham-diagram-panel,snuids-radar-panel,fatcloud-windrose-panel,pr0ps-trackmap-panel
      VIRTUAL_HOST: lnsmonit.MYDOMAIN.ORG
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: grafana
    volumes:
       - ./configuration/grafana/grafana.ini:/etc/grafana/grafana.ini
#       - ./configuration/grafana/dashboards/:/var/lib/grafana/dashboards/
#       - ./configuration/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
       - ./configuration/grafana/datasources/:/etc/grafana/provisioning/datasources/
       - ./configuration/grafana/logo.svg:/usr/share/grafana/public/img/grafana_icon.svg
    ports:
      - 3000:3000
    restart: unless-stopped
    network_mode: bridge

